version: "3.9"

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}

services:
  web:
    build:
      context: .
      target: demo-cdk-development
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    ports:
      - 80:80
    volumes:
      - ./:/home/node/app
    extra_hosts: # For Linux
      - host.docker.internal:host-gateway
    tty: true
    expose:
      - 3000
    command: "npm run dev"
